# Clean and wrangle data
## Setup
```{r}
library(dplyr)
library(tidyr)
library(readr)
```

## Source data
```{r}
catch_original <- read_csv(file = "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")
```

```{r}
colnames(catch_original)
head(catch_original)
summary(catch_original)
glimpse(catch_original)
```

## clean and reshape data

```{r}
catch_data <- catch_original %>% 
    select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)
```


```{r}
catch_clean <- catch_data %>%
    dplyr::mutate(
        Chinook = dplyr::if_else(condition = Chinook == "I", 
            true = "1",
            false = Chinook),
        Chinook = as.numeric(Chinook))
```

 
 ```{r}
 catch_long <- catch_clean %>% 
    pivot_longer(col= -c (Region, Year),
    names_to = "species",
    values_to = "catch_thousands"
    )
 ```

 
 ```{r}
 catch_wide <- catch_long %>% 
    pivot_wider(
        names_from = species,
        values_from = catch_thousands
    )
    head(catch_wide)
 ```

 
 ```{r}
 catch_long <- catch_long %>% 
    mutate(catch=catch_thousands* 1000) %>% 
    select(-catch_thousands)
head(catch_long)
 ```

 
 ```{r}
 mean_region <- catch_long %>%
    group_by(Region) %>%
    summarize(mean_catch = mean(catch, na.rm = TRUE), .groups= "drop") %>% 
    arrange(desc(mean_catch))

# Check the result
head(mean_region)
 ```

 
 ```{r}
 sse_catch <- catch_long %>% 
    filter(Region=="COP")

head(sse_catch)
 
 ```

 ## experiment with unite and separate

 
 ```{r}
 sites_df <- data.frame(site = c("HAW-101", "HAW-103", "OAH-320", "OAH-219", "MAU-039"))
sites_df %>% 
    separate_wider_delim(cols=site, delim = "-",
    names = c("island", "site_number"),
    cols_remove = FALSE)

 ```

 
 ```{r}
 dates_df %>% 
    unite 
 ```
